#### Pandas-DataFrame and Series

###### pandas is a powerful data manipulation library in python,widely used for data analysis and data cleaning. It provides two primary data stuctures. Series and DataFrame. A series is a one-dimensional array-like object,while a Dataframe is a two-dimensional,size-mutable, and potentially heterogenous tabular data structure with lebeled axes(rows and columns)

In [1]:
import pandas as pd

In [2]:
## Series

import pandas as pd
data=[1,2,3,4,5]
series= pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [3]:
## Create a Series from dicrtionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [4]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
## Dataframe
## Create a Dataframe from a dictionary oof list

data={
    'Name':['Barsha', 'Shayra', 'Mayra'],
    'Age':[24,25,28],
    'City':['Dahka','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0  Barsha   24     Dahka
1  Shayra   25  New York
2   Mayra   28   Florida
<class 'pandas.DataFrame'>

In [11]:
## Create a Data Frame from a list of Dictionries

data=[
    {'Name':'Barsha','Age':24,'City':'Dhaka'},
    {'Name':'Nila','Age':19,'City':'Dhaka'},
    {'Name':'Raisha','Age':27,'City':'Dhaka'},
    {'Name':'Halima','Age':22,'City':'Dhaka'}    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age   City
0  Barsha   24  Dhaka
1    Nila   19  Dhaka
2  Raisha   27  Dhaka
3  Halima   22  Dhaka
<class 'pandas.DataFrame'>

In [7]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [8]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
20,10021,2024-01-21,Electronics,Sony WH-1000XM5 Headphones,2,349.99,699.98,Asia,Debit Card
21,10022,2024-01-22,Home Appliances,Panasonic Rice Cooker,3,89.99,269.97,Europe,Credit Card
22,10023,2024-01-23,Clothing,Zara Jacket,2,99.99,199.98,North America,PayPal
23,10024,2024-01-24,Beauty Products,Dove Body Lotion,5,10.99,54.95,Asia,Debit Card
24,10025,2024-01-25,Sports,Spalding Basketball,3,29.99,89.97,Europe,Credit Card

In [12]:
## Accessing Data from DataFrame
df

     Name  Age   City
0  Barsha   24  Dhaka
1    Nila   19  Dhaka
2  Raisha   27  Dhaka
3  Halima   22  Dhaka

In [14]:
df['Name']

0    Barsha
1      Nila
2    Raisha
3    Halima
Name: Name, dtype: str

In [19]:
print(type(df))

<class 'pandas.DataFrame'>

In [20]:
print(df.head())

     Name  Age   City
0  Barsha   24  Dhaka
1    Nila   19  Dhaka
2  Raisha   27  Dhaka
3  Halima   22  Dhaka

In [24]:
df.iloc[0,2]

'Dhaka'

In [28]:
## Accessing a specified element
df.at[2,'Age']

np.int64(27)

In [29]:
df.at[2,'Name']

'Raisha'

In [30]:
## Accessing a specified element using iat
df.iat[2,2]

'Dhaka'

In [31]:
df

     Name  Age   City
0  Barsha   24  Dhaka
1    Nila   19  Dhaka
2  Raisha   27  Dhaka
3  Halima   22  Dhaka

In [34]:
## Data Manipulation with DataFrame
df

     Name  Age   City
0  Barsha   24  Dhaka
1    Nila   19  Dhaka
2  Raisha   27  Dhaka
3  Halima   22  Dhaka

In [37]:
## Adding cloumn
df['Salary']=[50000,60000,70000,45000]
df

     Name  Age   City  Salary
0  Barsha   24  Dhaka   50000
1    Nila   19  Dhaka   60000
2  Raisha   27  Dhaka   70000
3  Halima   22  Dhaka   45000

In [40]:
## Remove a column
df.drop('Salary', axis=1,inplace=True)

In [41]:
df

     Name  Age   City
0  Barsha   24  Dhaka
1    Nila   19  Dhaka
2  Raisha   27  Dhaka
3  Halima   22  Dhaka

In [42]:
## Add age tothe column
df['Age']=df['Age']+1
df

     Name  Age   City
0  Barsha   25  Dhaka
1    Nila   20  Dhaka
2  Raisha   28  Dhaka
3  Halima   23  Dhaka

In [45]:
df.drop(0,inplace=True)
df

     Name  Age   City
1    Nila   20  Dhaka
2  Raisha   28  Dhaka
3  Halima   23  Dhaka

In [46]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [50]:
## Display the Data types of each column
print("Data types:\n", df.dtypes)

##Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical summary:
        Transaction ID  Units Sold  Unit Price  Total Revenue
count       25.000000   25.000000   25.000000       25.00000
mean     10013.000000    2.720000  203.150000      318.61280
std          7.359801    1.486607  293.472696      426.10822
min      10001.000000    1.000000    8.990000       37.98000
25%      10007.000000    2.000000   19.990000       74.95000
50%      10013.000000    2.000000   74.990000      179.98000
75%      10019.000000    4.000000  199.990000      399.98000
max      10025.000000    6.000000  999.990000     1999.98000

In [51]:
df.describe()

       Transaction ID  Units Sold  Unit Price  Total Revenue
count       25.000000   25.000000   25.000000       25.00000
mean     10013.000000    2.720000  203.150000      318.61280
std          7.359801    1.486607  293.472696      426.10822
min      10001.000000    1.000000    8.990000       37.98000
25%      10007.000000    2.000000   19.990000       74.95000
50%      10013.000000    2.000000   74.990000      179.98000
75%      10019.000000    4.000000  199.990000      399.98000
max      10025.000000    6.000000  999.990000     1999.98000