#### Data Manipulation and Analysis with Pandas

###### Data Manipulation nd analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and anlysis., making it easier to clran, trasform, and extract insights from data. In this lesson, we will cover variour data manipulation and analysis techniques using Pandas.

In [11]:
import pandas as pd

In [24]:
df= pd.read_csv('data.csv')
## Fecth the first 5 rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [25]:
df.tail(5)

          Date Category  Value   Product  Sales Region
25  2023-01-26        B   24.0  Product1  455.0  South
26  2023-01-27        A   41.0  Product2  845.0   West
27  2023-01-28        C   30.0  Product3  605.0  North
28  2023-01-29        B   17.0  Product1  295.0   East
29  2023-01-30        A   46.0  Product2  995.0  South

In [5]:
df.describe()

           Value        Sales
count  30.000000    30.000000
mean   30.733333   620.600000
std    11.764744   283.068726
min     8.000000   110.000000
25%    22.500000   406.000000
50%    30.500000   612.500000
75%    39.750000   831.250000
max    51.000000  1250.000000

In [6]:
df.dtypes

Date            str
Category        str
Value       float64
Product         str
Sales       float64
Region          str
dtype: object

In [13]:
type(df)

pandas.DataFrame

In [15]:
## Handling Missing Values
df.isnull().any()

Date        False
Category    False
Value       False
Product     False
Sales       False
Region      False
dtype: bool

In [18]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [20]:
df.filled=df.fillna(0)

In [28]:
df.columns

Index(['Date', 'Category', 'Value', 'Product', 'Sales', 'Region',
       'Sales_fillna'],
      dtype='str')

In [30]:
## Filling missing values with the mean of the column
df['Sales_fillna']=df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product   Sales Region  Sales_fillna
0   2023-01-01        A   28.0  Product1   754.0   East         754.0
1   2023-01-02        B   39.0  Product3   110.0  North         110.0
2   2023-01-03        C   32.0  Product2   398.0   East         398.0
3   2023-01-04        B    8.0  Product1   522.0   East         522.0
4   2023-01-05        B   26.0  Product3   869.0  North         869.0
5   2023-01-06        A   45.0  Product2   650.0  South         650.0
6   2023-01-07        C   19.0  Product1   320.0   West         320.0
7   2023-01-08        B   51.0  Product3   980.0  North         980.0
8   2023-01-09        A   14.0  Product2   270.0   East         270.0
9   2023-01-10        C   37.0  Product1   745.0  South         745.0
10  2023-01-11        B   22.0  Product2   430.0   West         430.0
11  2023-01-12        A   48.0  Product3  1120.0  North        1120.0
12  2023-01-13        C   31.0  Product1   560.0   East         560.0
13  2023-01-14        B   16.0  Product2   285.0  South         285.0
14  2023-01-15        A   42.0  Product3   910.0   West         910.0
15  2023-01-16        C   25.0  Product1   470.0  North         470.0
16  2023-01-17        B   33.0  Product2   620.0   East         620.0
17  2023-01-18        A   29.0  Product3   790.0  South         790.0
18  2023-01-19        C   18.0  Product2   340.0   West         340.0
19  2023-01-20        B   40.0  Product1   860.0  North         860.0
20  2023-01-21        A   36.0  Product2   710.0   East         710.0
21  2023-01-22        C   27.0  Product3   540.0  South         540.0
22  2023-01-23        B   13.0  Product1   230.0   West         230.0
23  2023-01-24        A   50.0  Product2  1250.0  North        1250.0
24  2023-01-25        C   35.0  Product3   690.0   East         690.0
25  2023-01-26        B   24.0  Product1   455.0  South         455.0
26  2023-01-27        A   41.0  Product2   845.0   West         845.0
27  2023-01-28        C   30.0  Product3   605.0  North         605.0
28  2023-01-29        B   17.0  Product1   295.0   East         295.0
29  2023-01-30        A   46.0  Product2   995.0  South         995.0

In [31]:
df.dtypes

Date                str
Category            str
Value           float64
Product             str
Sales           float64
Region              str
Sales_fillna    float64
dtype: object

In [32]:
## Renaming Columns
df.rename(columns={'Date':'Sale Date'})
df.head()

         Date Category  Value   Product  Sales Region  Sales_fillna
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [35]:
## Change datatypes
df['Value_new']=df['Value'].fillna (df['Value'].mean()).astype(int)
df.head()

         Date Category  Value   Product  Sales Region  Sales_fillna  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26